import React, { useState } from 'react';
import styled from 'styled-components';
import { FaRobot, FaCheckCircle, FaTimesCircle, FaSpinner } from 'react-icons/fa';
import Card from '../components/UI/Card';
import Input from '../components/UI/Input';
import Button from '../components/UI/Button';
import { useResume } from '../context/ResumeContext';

const PageContainer = styled.div`
  max-width: 1000px;
  margin: 0 auto;
  padding: 2rem;
`;

const PageTitle = styled.h1`
  font-size: 2rem;
  margin-bottom: 2rem;
  color: #333;
`;

const HelperCard = styled.div`
  background: linear-gradient(135deg, rgba(74, 108, 247, 0.08), rgba(151, 71, 255, 0.1));
  padding: 1rem 1.5rem;
  border-radius: 12px;
  margin-bottom: 1.5rem;
  color: #3f4b5d;

  strong {
    color: #1e293b;
  }
`;

const TwoColumnLayout = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 2rem;

  @media (max-width: 992px) {
    grid-template-columns: 1fr;
  }
`;

const ScoreContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 2rem;
  background-color: #f8f9fa;
  border-radius: 12px;
  text-align: center;
`;

const ScoreCircle = styled.div`
  width: 160px;
  height: 160px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: ${({ score }) => {
    if (score >= 80) return 'linear-gradient(135deg, #a8e063 0%, #56ab2f 100%)';
    if (score >= 60) return 'linear-gradient(135deg, #ffb347 0%, #ffcc33 100%)';
    return 'linear-gradient(135deg, #ff512f 0%, #dd2476 100%)';
  }};
  color: white;
  font-size: 3rem;
  font-weight: 700;
  margin-bottom: 1.5rem;
  box-shadow: 0 4px 15px rgba(0, 0, 0, 0.15);
`;

const ScoreExplanation = styled.p`
  margin-bottom: 1.5rem;
  color: #555;
  font-size: 1.1rem;
  max-width: 500px;
`;

const ScoreSection = styled.div`
  margin-top: 2rem;
  width: 100%;
`;

const SectionTitle = styled.h3`
  color: #333;
  margin-bottom: 1rem;
  display: flex;
  align-items: center;
  gap: 8px;
`;

const KeywordsList = styled.ul`
  list-style-type: none;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 1.5rem;
`;

const KeywordItem = styled.li`
  background-color: ${({ matched }) => matched ? '#e3f4ea' : '#fee8eb'};
  color: ${({ matched }) => matched ? '#00a376' : '#ff5470'};
  padding: 0.4rem 0.8rem;
  border-radius: 4px;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  gap: 6px;
`;

const SuggestionsList = styled.ul`
  padding-left: 1.5rem;
  margin-bottom: 1.5rem;

  li {
    margin-bottom: 0.5rem;
    color: #555;
  }
`;

const Spinner = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 2rem;

  svg {
    animation: spin 1s linear infinite;
    color: #4a6cf7;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
`;

const ATSScorer = () => {
  const {
    calculateATSScore,
    atsScore,
    setJobDescription,
    jobDescription,
    loading
  } = useResume();

  const [resumeText, setResumeText] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    await calculateATSScore(resumeText, jobDescription);
  };

  return (
    <PageContainer>
      <PageTitle>ATS Score Analyzer</PageTitle>

      <Card>
        <HelperCard>
          <strong>Tip:</strong> Paste the exact job description so the AI can surface missing keywords and format improvements.
        </HelperCard>
        <form onSubmit={handleSubmit}>
          <Input
            label="Job Description"
            id="jobDescription"
            multiline
            rows={6}
            value={jobDescription}
            onChange={(e) => setJobDescription(e.target.value)}
            placeholder="Paste the job description here..."
            required
          />

          <Input
            label="Resume Content"
            id="resumeText"
            multiline
            rows={10}
            value={resumeText}
            onChange={(e) => setResumeText(e.target.value)}
            placeholder="Paste your resume content here or use the one generated by our AI..."
            required
          />

          <Button
            type="submit"
            disabled={loading || !jobDescription || !resumeText}
            style={{ marginTop: '1rem' }}
            fullWidth
          >
            {loading ? 'Analyzing...' : 'Analyze Resume'}
          </Button>
        </form>
      </Card>

      {loading && (
        <Card style={{ marginTop: '2rem' }}>
          <Spinner>
            <FaSpinner size={48} />
          </Spinner>
        </Card>
      )}

      {!loading && atsScore && (
        <Card style={{ marginTop: '2rem' }}>
          <TwoColumnLayout>
            <ScoreContainer>
              <ScoreCircle score={atsScore.score}>
                {atsScore.score}%
              </ScoreCircle>
              <ScoreExplanation>
                {atsScore.explanation}
              </ScoreExplanation>
            </ScoreContainer>

            <div>
              <ScoreSection>
                <SectionTitle>
                  <FaCheckCircle size={20} color="#00a376" /> Matched Keywords
                </SectionTitle>
                <KeywordsList>
                  {atsScore.matchedKeywords.map((keyword, index) => (
                    <KeywordItem key={index} matched>
                      <FaCheckCircle size={12} /> {keyword}
                    </KeywordItem>
                  ))}
                </KeywordsList>
              </ScoreSection>

              <ScoreSection>
                <SectionTitle>
                  <FaTimesCircle size={20} color="#ff5470" /> Missing Keywords
                </SectionTitle>
                <KeywordsList>
                  {atsScore.missingKeywords.map((keyword, index) => (
                    <KeywordItem key={index} matched={false}>
                      <FaTimesCircle size={12} /> {keyword}
                    </KeywordItem>
                  ))}
                </KeywordsList>
              </ScoreSection>

              <ScoreSection>
                <SectionTitle>
                  <FaRobot size={20} color="#4a6cf7" /> Improvement Suggestions
                </SectionTitle>
                <SuggestionsList>
                  {atsScore.suggestions.map((suggestion, index) => (
                    <li key={index}>{suggestion}</li>
                  ))}
                </SuggestionsList>
              </ScoreSection>
            </div>
          </TwoColumnLayout>
        </Card>
      )}
    </PageContainer>
  );
};

export default ATSScorer;
